### ISSUE TITLE
Time to use `build` from `setuptools` instead of `distutils`?

### ISSUE THREAD

**Issue by abravalheri** [elebihan/yaprogen#4]
The following feature in setuptools has been deprecated for almost 2 years and is about to be removed:

https://github.com/pypa/setuptools/blob/1ed759173983656734c3606e9c97a348895e5e0c/setuptools/command/build.py#L13-L27

It might be a good idea to import `build` directly from setuptools for the following code:

https://github.com/elebihan/yaprogen/blob/76b73c53a78f6274b57f6aafd29f996e9f41e7a0/disthelpers.py#L180-L181

(`build` is available directly from setuptools, starting on version v62.4.0)

**Comment by elebihan** [comment]
Thanks for reporting this issue. It should be fixed by #5.
